services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=cataloguedb
      - POSTGRES_USER=catalogueuser
      - POSTGRES_PASSWORD=cataloguepass
      - REDIS_HOST=redis
      - REDIS_PORT=6380

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cataloguedb
      POSTGRES_USER: catalogueuser
      POSTGRES_PASSWORD: cataloguepass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6380"

volumes:
  db_data:
